wandb_version: 1

MaxEpochs:
  value: 100
atom_fea_len:
  value: 60
batch_size:
  value: 8
h_fea_len:
  value: 241
log_lr:
  value: -3
n_conv:
  value: 4
n_h:
  value: 4
reduceLR_patience:
  value: 14
