wandb_version: 1

MaxEpochs:
  value: 100
atom_fea_len:
  value: 159
batch_size:
  value: 12
h_fea_len:
  value: 84
log_lr:
  value: -2
n_conv:
  value: 2
n_h:
  value: 2
reduceLR_patience:
  value: 20
