wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750534492.497411
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 105
      3:
      - 23
      - 37
      4: 3.10.11
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
atom_fea_len:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 16
h_fea_len:
  desc: null
  value: 198
log_lr:
  desc: null
  value: -3
n_conv:
  desc: null
  value: 3
n_h:
  desc: null
  value: 1
reduceLR_patience:
  desc: null
  value: 15
