wandb_version: 1

MaxEpochs:
  value: 100
atom_fea_len:
  value: 166
batch_size:
  value: 8
h_fea_len:
  value: 137
log_lr:
  value: -3
n_conv:
  value: 3
n_h:
  value: 2
reduceLR_patience:
  value: 22
