wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1750732133.64116
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
MaxEpochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 12
len_embedding_feature_vector:
  desc: null
  value: 64
log_lr:
  desc: null
  value: -5
multiplicity_irreps:
  desc: null
  value: 16
num_conv:
  desc: null
  value: 3
num_hidden_feature:
  desc: null
  value: 64
num_hidden_layer:
  desc: null
  value: 0
num_radial_neurons:
  desc: null
  value: 64
num_radical_basis:
  desc: null
  value: 10
reduceLR_patience:
  desc: null
  value: 22
